name: Prep the rocket!

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check-skip-commmit:
    runs-on: ubuntu-latest
    name: 'Check commit should be skipped'
    steps:
      - name: Check
        run: |
          REGEX="^v\d\.\d\.\d$"
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          ! echo $COMMIT_MSG | grep -iqE "$REGEX"

  lint:
    needs: ['check-skip-commmit']
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Prettier
        run: yarn prettier:check

  unit-tests:
    name: Unit tests
    needs: ['check-skip-commmit']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Unit tests
        run: yarn test:unit

  mutation-tests:
    name: Mutation tests
    needs: ['check-skip-commmit']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.5

      - name: Cache Stryker incremental test ouputØ
        id: cache-stryker-incremental-output
        uses: actions/cache@v3
        env:
          cache-name: stryker-incremental-output
        with:
          path: ${{ github.workspace }}/reports/.mutation-incremental.json
          key: ${{ env.cache-name }}-${{ steps.branch-name.outputs.current_branch }}-${{ github.run_id }}
          restore-keys: |
            ${{ env.cache-name }}-${{ steps.branch-name.outputs.current_branch }}-

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Mutation tests
        run: yarn test:mutation

  version-tag:
    name: Version tag
    runs-on: ubuntu-latest
    needs: [lint, unit-tests, mutation-tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Calculate semantic version
        id: semantic-version
        uses: paulhatch/semantic-version@v4.0.3
        with:
          tag_prefix: 'v'
          major_pattern: '(MAJOR)'
          minor_pattern: '(MINOR)'
          format: '${major}.${minor}.${patch}'
          # change_path: src/ yarn.lock tsconfig.json .vscodeignore
          bump_each_commit: false

      - name: Setup git config
        if: steps.semantic-version.outputs.version == true
        run: |
          git config user.name "GitHub Actions Versioning Workflow"
          git config user.email "<>"

      - name: Tag
        if: steps.semantic-version.outputs.version == true
        run: |
          export VERSION=${{ steps.semantic-version.outputs.version }}
          yarn version --new-version "${VERSION:1}"
          git push --no-verify
          git push origin "${VERSION}" --no-verify
