name: Launch the rocket!

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests & stuff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Lint
        run: npm run lint

      - name: Unit tests
        run: npm run test:unit