name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Versioning Workflow"
          git config user.email "<>"

      - name: Package
        run: |
          npx vsce package ${{github.ref_name}} -m "[skip-ci packaged %s]"
          git push --no-verify

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: stryker-runner-${{github.ref_name}}.vsix
          fail_on_unmatched_files: true
