name: Launch the rocket!

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  github-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Versioning Workflow"
          git config user.email "<>"

      - name: Make version
        id: make-version
        run: |
          VERSION=${{ github.ref_name }}
          echo "::set-output name=VERSION::${VERSION:1}"

      - name: Package
        run: |
          npx vsce package ${{ steps.make-version.outputs.VERSION }} -m "[skip ci v%s]"
          git tag -d ${{ steps.make-version.outputs.VERSION }}
          git push --no-verify

      - name: Release to Github
        uses: softprops/action-gh-release@v1
        with:
          files: stryker-runner-${{ steps.make-version.outputs.VERSION }}.vsix
          fail_on_unmatched_files: true

      - name: Release to VSCode Marketplace
        env:
          VSCE_PAT: ${{ secrets.VCSE_PAT_TOKEN }}
        run: npx vsce publish --no-git-tag-version --no-update-package-json -i "stryker-runner-${{ steps.make-version.outputs.VERSION }}.vsix"
